// This file is used as the startup file for the cPanel Node.js App
// It requires the standalone server generated by Next.js
// Make sure to run `npm run build` first, and ensure `output: "standalone"` is in next.config.ts

require('./.next/standalone/server.js');
